awslabs/aws-embedded-metrics-node

README.md
In the README you're calling `metrics.flush()` without awaiting it. This means that execution of subsequent functions will continue even though `metrics.flush()` may not have completed. It also means that exceptions won't correctly be captured by the async block.
In your tests you're correctly awaiting it, but if ppl use this in their code as currently documented in the README they could run into some tricky to debug concurrency problems (and potential unhandled promises being thrown)
=> metrics.flush() needs to be awaited (or returned)

package-lock.json
*Issue #, if available:* N/A
*Description of changes:* I recently went to install this package and its dependencies and found the [package-lock.json](https://github.com/awslabs/aws-embedded-metrics-node/blob/master/package-lock.json#L3) version was out of sync with the [package.json](https://github.com/awslabs/aws-embedded-metrics-node/blob/master/package.json#L3) version.
This PR fixes that.
=> Fix package-lock version error

README.md, src/logger/MetricScope.ts, src/logger/__tests__/MetricScope.test.ts
N/A
When trying to use the [metricScope](https://github.com/awslabs/aws-embedded-metrics-node/blob/master/src/logger/MetricScope.ts) with function parameters, I noticed that the input arguments were being cast as `any[]`.
This is dangerous and can lead to cases where users are able to declare something like this:
```typescript
const myFunc = metricScope(metrics => async (param1: string, param2: number) => { ... });
```
but then (accidentally) call it like this which can cause runtime errors:
```
myFunc(0, 'myParam'); // Ahhhhh I accidentally put the parameters in the wrong order!!
```
This PR fixes this by preserving the `args` typing information via using generics and having the generic extend `readonly unknown[]` which is the immutable, …
=> Preserve the metricScope function parameter typing using generics

package-lock.json
N/A
After installing this package, I got a warning from NPM saying that this repo contains 2 high severity and 2 low severity vulnerabilities.
Running `npm audit` yielded this:
```
> npm audit
=== npm audit security report ===                        
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ mem                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ npm-pack-zip [dev]                                           │ …
```
=> Fix 2 high severity and 2 low severity vulnerabilities

src/logger/MetricsLogger.ts, src/logger/__tests__/MetricsLogger.test.ts
=> fix(#15): preserve the logger context across flushes

README.md, src/config/EnvironmentConfigurationProvider.ts, src/config/IConfiguration.ts, src/config/__tests__/EnvironmentConfigurationProvider.test.ts, src/environment/EnvironmentDetector.ts, src/environment/Environments.ts, src/environment/LambdaEnvironment.ts, src/environment/LocalEnvironment.ts, src/environment/__tests__/EnvironmentDetector.test.ts, src/environment/__tests__/LambdaEnvironment.test.ts, src/environment/__tests__/LocalEnvironment.test.ts, src/index.ts, src/sinks/ConsoleSink.ts, src/sinks/__tests__/ConsoleSink.test.ts
Closes #18 
- adds LocalEnvironment
- renames LambdaSink to ConsoleSink
- short-circuits environment discovery if override is specified
- adds environment override
- fixes environment detection so that it only runs once after module load
TODO:
=> Allow overriding environment and provide LocalEnvironment

README.md
N/A
Currently, the README says that you can override the environment using a `AWS_EMF_AGENT_ENDPOINT` environment variable.
This is a typo and it is meant to be `AWS_EMF_ENVIRONMENT` as specified [here](https://github.com/awslabs/aws-embedded-metrics-node/blob/f718aac9bf08ada0e1c7c3ebf1857273d7f1e091/src/config/EnvironmentConfigurationProvider.ts#L28).
=> Fixes environment override typo in the README

src/environment/DefaultEnvironment.ts, src/environment/__tests__/DefaultEnvironment.test.ts, src/sinks/AgentSink.ts, src/sinks/__tests__/AgentSink.test.ts
Closes #17 
Some agents (such as Fluent-Bit) handle LogGroup configuration in the agent directly. By allowing the LogGroup to be optional, we provide better support for these scenarios without including some arbitrary and incorrect LogGroup name in the payload
=> #17 generic agent support

src/Constants.ts, src/serializers/__tests__/LogSerializer.test.ts
The backend will fail to parse entries with more than 9 dimensions.
=> Set MAX_DIMENSIONS=9

package.json, src/sinks/__tests__/AgentSink.test.ts, src/sinks/__tests__/TcpClient.test.ts, src/sinks/connections/TcpClient.ts
Closes #32 
The `error` listener was added to catch `ECONNREFUSED` prior to actually writing to the socket. If the connection is not open then the `write` callback will not be executed. The actual bug here is that `sendMessage` is supposed to be checking if the connection can be written to. We assume the connection has been established because `this.socket.writable` is `true`, but the socket is not actually open yet (e.g. may be writeable but readyState is `opening`).
https://github.com/awslabs/aws-embedded-metrics-node/blob/8bc900218ab18d2fca59bf29211c77d366f83e66/src/sinks/connections/TcpClient.ts#L44-L45
=> Fix memory leak in TCP client

examples/README.md, examples/ecs-firelens/.gitignore, examples/ecs-firelens/Dockerfile, examples/ecs-firelens/app.js, examples/ecs-firelens/container-definitions.template.json, examples/ecs-firelens/fluent-bit.conf, examples/ecs-firelens/package-lock.json, examples/ecs-firelens/package.json, examples/ecs-firelens/publish.sh, package-lock.json, package.json, src/Constants.ts, src/environment/ECSEnvironment.ts, src/environment/EnvironmentDetector.ts, src/environment/Environments.ts, src/environment/__tests__/ECSEnvironment.test.ts, src/environment/__tests__/EnvironmentDetector.test.ts
- add ECSEnvironment
- bump TypeScript to 3.8
- bump lint tooling and fix-lint
- add ECSEnvironment tests
- use mocks in the environment detector tests
- update docs
- npm audit fix
Closes #17 
Closes #27 
=> add ECS environment with FireLens support

bin/run-integ-tests.sh, examples/eks/Dockerfile, examples/eks/README.md, examples/eks/app.js, examples/eks/cwagent-configmap.yaml, examples/eks/kubernetes/deployment.yaml, examples/eks/kubernetes/service.yaml, examples/eks/package-lock.json, examples/eks/package.json, package-lock.json, src/sinks/AgentSink.ts, test/integ/agent/Dockerfile
=> Add EKS example

README.md, src/config/EnvironmentConfigurationProvider.ts, src/config/IConfiguration.ts, src/config/__tests__/EnvironmentConfigurationProvider.test.ts, src/logger/MetricsContext.ts
Closed #39
Allows setting namespace via the AWS_EMF_NAMESPACE environment variable or via the configuration object
=> Allow setting namespace via an environment variable

README.md
*Pull Request/Issue #, if available:* [28](https://github.com/awslabs/aws-embedded-metrics-node/pull/28)
I can see that support for ECS and firelens was added on the previously mentioned PR.
I can also see that the [code](https://github.com/awslabs/aws-embedded-metrics-node/blob/730bbaeb341ee3952a404c04fc1de59a6ec65cf5/src/environment/EnvironmentDetector.ts#L50-L51) for Environment Overrides supports the `ECS` value, yet we do not mention it in the documentation as a supported value:
```
const getEnvironmentFromOverride = (): IEnvironment | undefined => {
// short-circuit environment detection and use override
switch (config.environmentOverride) {
case Environments.Agent:
return defaultEnvironment;
case Environments.EC2:
return ec2Environment;
case …
```
=> Added ECS as a supported Env Override on README.md

src/sinks/connections/TcpClient.ts
https://github.com/awslabs/aws-embedded-metrics-node/issues/58
Before this change I get this when testing with node v14:
```
Resolving environment
Discovering environment
Testing: LambdaEnvironment
Testing: EC2Environment
Socket timeout while connecting to 'http://169.254.169.254/latest/dynamic/instance-identity/document'
Unknown ServiceName.
Unknown ServiceName.
Unknown ServiceType.
Received default dimensions {
LogGroup: 'Unknown-metrics',
ServiceName: 'Unknown',
ServiceType: 'Unknown'
}
Unknown ServiceName.
Getting socket client for connection. { host: '0.0.0.0', port: 25888, protocol: 'tcp:' }
Using socket client TcpClient
TcpClient data was not flushed to kernel buffer and was queued in memory.
Failed to write Error [ERR_SOCKET_CLOSED]: Socket is closed
at …
```
=> Fix 'Socket is closed' error on node v14

RELEASE_NOTES.md
I looked at `RELEASE_NOTES.md` for information about the latest releases and was confused by their absence. Then I found all the notes in the GitHub Releases page. This PR suggests using the Releases list as the sole source of release notes.
An alternative approach is to delete `RELEASE_NOTES.md`.
=> Deduplicate RELEASE_NOTES and Releases list

README.md, src/logger/MetricsContext.ts, src/logger/MetricsLogger.ts, src/logger/__tests__/MetricsLogger.test.ts
*Issue #, if available:* 61
https://github.com/awslabs/aws-embedded-metrics-node/issues/61
Adds the MetricsLogger.setTimestamp() method.
One aspect I think core maintainers will have a much better sense of, if I set the timestamp should that be preserved across calls to `flush()`? I wasn't 100% sure what would be desired behaviour, so I took a guess and went for "yes, if set explicitly, preserve". For my own use case described in #61, I will be calling `setTimeout` in 100% of `MetricsContext` instances generated, so it would be irrelevant anyway.
Another guess I made was that if the timestamp is not set explicitly, the `MetricsContext` should reset the `meta.Timestamp` field to `new Date()`. I think this is less surprising behaviour for users who never call …
=> Allow setting timestamp of metrics.

src/logger/MetricsContext.ts, src/logger/__tests__/MetricsContext.test.ts
*Issue #71*
Using shouldUseDefaultDimensions to populate new MetricsContext on copy.
=> Copy shouldUseDefaultDimensions to new MetricsContext

src/logger/MetricsContext.ts
The latter is preferred and more efficient.
=> new Date().getTime() -> Date.now()

src/logger/MetricScope.ts, src/logger/__tests__/MetricScope.test.ts
`metricScope` now lets the regular try-catch-finally semantics be
responsible for propagating any errors from the handler instead of
rethrowing them manually. This allows the wrapper's return type to
mirror the handler more accurately, eliminating the `| undefined`.
=> Simplify error handling in MetricScope wrapper

src/logger/MetricsLogger.ts, src/logger/__tests__/MetricsLogger.test.ts, test/utils/TestSink.ts
*Issue #81*
- Added 'await' in the MetricsLogger
- Added a test for checking the behavior (I added a describe block around the existing tests and added a second describe to setup a TestSink where the accept function rejects. So it looks like a large change on the diff but most lines only got 2 extra spaces because they became part of the first describe block)
=> Fix #81 (crash when no connection to agent)

package-lock.json, package.json
https://github.com/advisories/GHSA-c4w7-xm78-47vh
The npm package y18n before versions 3.2.2, 4.0.1, and 5.0.5 is vulnerable to Prototype Pollution.
=> fix high sev CVE-2020-7774 in build deps

src/environment/EC2Environment.ts, src/environment/ECSEnvironment.ts, src/environment/__tests__/ECSEnvironment.test.ts, src/logger/MetricsContext.ts, src/utils/Fetch.ts, test/integ/agent/Dockerfile
N/A
IMDSv2 uses session authentication to retrieve EC2 instance metadata.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html
=> Migrate from IMDSv1 to IMDSv2

bin/publish-package.sh, bin/utils.sh
*Issue #, if available:* N/A
Deployment stage is failing due to `sh: jest: command not found`.
This change attempts to fix this issue by removing the command to delete `node_modules` in `publish-package.sh`.
This shouldn't have any effect on publishing since `npm publish` [ignores](https://docs.npmjs.com/cli/v8/commands/npm-publish) all files present in `.gitignore`.
Why wasn't this happening before? npm's `prepare` and `prepublishOnly` stages were unable to run in previous builds.
=> undo node_modules removal in pre-publish

package-lock.json, package.json, src/Constants.ts, src/exceptions/InvalidDimensionError.ts, src/logger/MetricsContext.ts, src/logger/__tests__/MetricsContext.test.ts, src/serializers/LogSerializer.ts, src/serializers/__tests__/LogSerializer.test.ts, src/utils/Validator.ts
*Issue #, if available:* #68
Related issues:
* https://github.com/awslabs/aws-embedded-metrics-python/issues/88
* https://github.com/awslabs/aws-embedded-metrics-java/issues/112
* https://github.com/awslabs/aws-embedded-metrics-dotnet/issues/35
Add function to strip non-ascii characters and stringify numbers for dimension values.
[UPDATE] Instead of silently dropping non-compliant characters, the client will now throw an error if an invalid dimension is found according to specifications [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_Dimension.html) (breaking change).
=> Add validation for dimension values

package-lock.json, package.json
`validator` was placed in devDependencies instead of dependencies.
=> Validator not imported properly

README.md, package-lock.json, package.json, src/sinks/ConsoleSink.ts, src/sinks/__tests__/ConsoleSink.test.ts
This change updates the ConsoleSink to switch from `console.log` and use `Console()` when Lambda log format is JSON.
=> Change ConsoleSink depending on Lambda log format

bin/deploy-canary.sh
ECS soak test is failing with error message
```
Error: Cannot find module '@datastructures-js/heap'
```
This PR updates the deploy script to copy all `node_module` dependencies to the docker image.
=> Update canary deploy script

package-lock.json, package.json, test/integ/agent/end-to-end.integ.ts
Fixes: https://github.com/awslabs/aws-embedded-metrics-node/issues/156
Migrate AWS SDK for JavaScript v2 APIs to v3 by running the following script:
```console
npx aws-sdk-js-codemod -t v2-to-v3 test/**/*.ts
```
=> Migrate AWS SDK for JavaScript v2 APIs to v3

bin/start-agent.sh
- Implement AWS STS assume-role to obtain short-term credentials
- Store credentials in environment variables for AWS CLI usage
- Update CloudWatch Agent configuration to use temporary credentials
- Improve security by eliminating long-term IAM user credentials
The change uses the CodeBuild execution role to generate temporary 
credentials with a 1-hour duration, enhancing security through 
credential rotation.
=> Replace User creds with Role creds for CWL agent

test/canary/agent/container-definitions.json
Changed cloudwatch agent dockerhub image to use ECR version instead, this is to be consistent with this PR: https://github.com/awslabs/aws-embedded-metrics-java/pull/164
=> changed dockerhub cw agent image to use ecr image
